# Site settings
title: "Программирование на Go (2026)"
author: "Kot-off"
locale: "ru"

# Если репозиторий называется golang-fundamentals-2026.io
# то в baseurl пишем именно это имя со слэшем в начале
baseurl: "/golang-fundamentals-2026.io"
url: "https://kot-off.github.io"

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - fabfile.py
  - .sass-cache
  - node_modules

# Collections
collections:
  book:
    output: true
    permalink: '/:name.html'

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title.html

# Assets configuration
assets:
  js_compressor: uglifier
  css_compressor: sass
  cache: false

# Markdown parsing
kramdown:
  input: GFM
  syntax_highlighter: rouge