# Site settings
title: "Программирование на Go (2026)"
author: "Kot-off"
locale: "ru"
url: "https://kot-off.github.io"
baseurl: "/golang-fundamentals-2026.io"

# Отключаем сторонние темы, чтобы работали наши стили
theme: null

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - fabfile.py
  - .sass-cache
  - node_modules

# Collections
collections:
  book:
    output: true
    permalink: '/:name.html'

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title.html

# Стандартные настройки SASS для Jekyll
sass:
  style: compressed
  sass_dir: assets/stylesheets

kramdown:
  input: GFM
  syntax_highlighter: rouge